export const StudentConstants = {
    GET_LIST_CLASS_OF_TERN_REQUEST: ' GET_LIST_CLASS_OF_TERN_REQUEST',
    GET_LIST_CLASS_OF_TERN_SUCCESS: ' GET_LIST_CLASS_OF_TERN_SUCCESS',
    GET_LIST_CLASS_OF_TERN_FAILURE: ' GET_LIST_CLASS_OF_TERN_FAILURE',

    GET_LIST_CLASS_OF_STUDENT_REQUEST: ' GET_LIST_CLASS_OF_STUDENT_REQUEST',
    GET_LIST_CLASS_OF_STUDENT_SUCCESS: ' GET_LIST_CLASS_OF_STUDENT_SUCCESS',
    GET_LIST_CLASS_OF_STUDENT_FAILURE: ' GET_LIST_CLASS_OF_STUDENT_FAILURE',

    REGISTER_CLASS_REQUEST: 'REGISTER_CLASS_REQUEST',
    REGISTER_CLASS_SUCCESS: 'REGISTER_CLASS_SUCCESS',
    REGISTER_CLASS_FAILURE: 'REGISTER_CLASS_FAILURE',
}