export const LecturerConstants = {
    GET_LIST_CLASS_OF_LEC_REQUEST: ' GET_LIST_CLASS_OF_LEC_REQUEST',
    GET_LIST_CLASS_OF_LEC_SUCCESS: ' GET_LIST_CLASS_OF_LEC_SUCCESS',
    GET_LIST_CLASS_OF_LEC_FAILURE: ' GET_LIST_CLASS_OF_LEC_FAILURE',

    INFO_CLASS_REQUEST: 'INFO_CLASS_REQUEST',
    INFO_CLASS_SUCCESS: 'INFO_CLASS_SUCCESS',
    INFO_CLASS_FAILURE: 'INFO_CLASS_FAILURE',

    SET_POINT_OF_STUDENT_REQUEST: 'SET_POINT_OF_STUDENT_REQUEST',
    SET_POINT_OF_STUDENT_SUCCESS: 'SET_POINT_OF_STUDENT_SUCCESS',
    SET_POINT_OF_STUDENT_FAILURE: 'SET_POINT_OF_STUDENT_FAILURE',
}