export const LecturerConstants = {
    GET_LIST_CLASS_OF_LEC_REQUEST: ' GET_LIST_CLASS_OF_LEC_REQUEST',
    GET_LIST_CLASS_OF_LEC_SUCCESS: ' GET_LIST_CLASS_OF_LEC_SUCCESS',
    GET_LIST_CLASS_OF_LEC_FAILURE: ' GET_LIST_CLASS_OF_LEC_FAILURE',
}