export const AdminConstants = {
    GET_SUBJECTS_REQUEST: 'GET_SUBJECTS_REQUEST',
    GET_SUBJECTS_SUCCESS: 'GET_SUBJECTS_SUCCESS',
    GET_SUBJECTS_FAILURE: 'GET_SUBJECTS_FAILURE',

    CREATE_SUBJECTS_REQUEST: 'CREATE_SUBJECTS_REQUEST',
    CREATE_SUBJECTS_SUCCESS: 'CREATE_SUBJECTS_SUCCESS',
    CREATE_SUBJECTS_FAILURE: 'CREATE_SUBJECTS_FAILURE',

    GET_SUBJECT_REQUEST: 'GET_SUBJECT_REQUEST',
    GET_SUBJECT_SUCCESS: 'GET_SUBJECT_SUCCESS',
    GET_SUBJECT_FAILURE: 'GET_SUBJECT_FAILURE',

    CREATE_SUBJECT_REQUEST: 'CREATE_SUBJECT_REQUEST',
    CREATE_SUBJECT_SUCCESS: 'CREATE_SUBJECT_SUCCESS',
    CREATE_SUBJECT_FAILURE: 'CREATE_SUBJECT_FAILURE',

    GET_TERN_REQUEST: 'GET_TERN_REQUEST',
    GET_TERN_SUCCESS: 'GET_TERN_SUCCESS',
    GET_TERN_FAILURE: 'GET_TERN_FAILURE',

    CREATE_TERN_REQUEST: 'CREATE_TERN_REQUEST',
    CREATE_TERN_SUCCESS: 'CREATE_TERN_SUCCESS',
    CREATE_TERN_FAILURE: 'CREATE_TERN_FAILURE',

    END_TERN_REQUEST: 'END_TERN_REQUEST',
    END_TERN_SUCCESS: 'END_TERN_SUCCESS',
    END_TERN_FAILURE: 'END_TERN_FAILURE',

    START_TERN_REQUEST: 'START_TERN_REQUEST',
    START_TERN_SUCCESS: 'START_TERN_SUCCESS',
    START_TERN_FAILURE: 'START_TERN_FAILURE',

    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST',
    EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',

    GET_SESSION_REQUEST: 'GET_SESSION_REQUEST',
    GET_SESSION_SUCCESS: 'GET_SESSION_SUCCESS',
    GET_SESSION_FAILURE: 'GET_SESSION_FAILURE',

    CREATE_SESSION_REQUEST: 'CREATE_SESSION_REQUEST',
    CREATE_SESSION_SUCCESS: 'CREATE_SESSION_SUCCESS',
    CREATE_SESSION_FAILURE: 'CREATE_SESSION_FAILURE',


    END_SESSION_REQUEST: 'END_SESSION_REQUEST',
    END_SESSION_SUCCESS: 'END_SESSION_SUCCESS',
    END_SESSION_FAILURE: 'END_SESSION_FAILURE',

    START_SESSION_REQUEST: 'START_SESSION_REQUEST',
    START_SESSION_SUCCESS: 'START_SESSION_SUCCESS',
    START_SESSION_FAILURE: 'START_SESSION_FAILURE',

    DELETE_SESSION_REQUEST: 'DELETE_SESSION_REQUEST',
    DELETE_SESSION_SUCCESS: 'DELETE_SESSION_SUCCESS',
    DELETE_SESSION_FAILURE: 'DELETE_SESSION_FAILURE',

    CREATE_CLASS_REQUEST: 'CREATE_CLASS_REQUEST',
    CREATE_CLASS_SUCCESS: 'CREATE_CLASS_SUCCESS',
    CREATE_CLASS_FAILURE: 'CREATE_CLASS_FAILURE',

    GET_CLASS_REQUEST: ' GET_CLASS_REQUEST',
    GET_CLASS_SUCCESS: ' GET_CLASS_SUCCESS',
    GET_CLASS_FAILURE: ' GET_CLASS_FAILURE',

    DELETE_CLASS_REQUEST: 'DELETE_CLASS_REQUEST',
    DELETE_CLASS_SUCCESS: 'DELETE_CLASS_SUCCESS',
    DELETE_CLASS_FAILURE: 'DELETE_CLASS_FAILURE',

    ASSIGNMENT_CLASS_REQUEST: ' ASSIGNMENT_CLASS_REQUEST',
    ASSIGNMENT_CLASS_SUCCESS: ' ASSIGNMENT_CLASS_SUCCESS',
    ASSIGNMENT_CLASS_FAILURE: ' ASSIGNMENT_CLASS_FAILURE',

    GET_LECTURER_REQUEST: ' GET_LECTURER_REQUEST',
    GET_LECTURER_SUCCESS: ' GET_LECTURER_SUCCESS',
    GET_LECTURER_FAILURE: ' GET_LECTURER_FAILURE',

    GET_LIST_CLASS_OF_LEC_REQUEST: ' GET_LIST_CLASS_OF_LEC_REQUEST',
    GET_LIST_CLASS_OF_LEC_SUCCESS: ' GET_LIST_CLASS_OF_LEC_SUCCESS',
    GET_LIST_CLASS_OF_LEC_FAILURE: ' GET_LIST_CLASS_OF_LEC_FAILURE',

    SET_POINT_OF_STUDENT_REQUEST: 'SET_POINT_OF_STUDENT_REQUEST',
    SET_POINT_OF_STUDENT_SUCCESS: 'SET_POINT_OF_STUDENT_SUCCESS',
    SET_POINT_OF_STUDENT_FAILURE: 'SET_POINT_OF_STUDENT_FAILURE',

    GET_STUDENTS_REQUEST: 'GET_STUDENTS_REQUEST',
    GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
    GET_STUDENTS_FAILURE: 'GET_STUDENTS_FAILURE',

    EDIT_STUDENT_REQUEST: 'EDIT_STUDENT_REQUEST',
    EDIT_STUDENT_SUCCESS: 'EDIT_STUDENT_SUCCESS',
    EDIT_STUDENT_FAILURE: 'EDIT_STUDENT_FAILURE',

    UPDATE_STUDENT_REQUEST: 'UPDATE_STUDENT_REQUEST',
    UPDATE_STUDENT_SUCCESS: 'UPDATE_STUDENT_SUCCESS',
    UPDATE_STUDENT_FAILURE: 'UPDATE_STUDENT_FAILURE',
}